# Light support
# Hue serial numbers can be found in secrets.yaml

# RFXtrx433XL lights, needs host restart for automatic_add change
- platform: rfxtrx
  automatic_add: False
#  devices:
#    "0b1100af01a2024602010f50": # S1
#      name: Matbord
#      fire_event: true

