# Weather and calculated/template sensors

# Calculated sensors
- platform: min_max
  name: Ute Temperature
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.sovrum_ute_temperature
    - sensor.malte_ute_temperature
    - sensor.lina_ute_temperature
    - sensor.entre_ute_temperature
#    - sensor.altan_ute_temperature # Gives bad mean value
- platform: min_max
  name: Inne Temperature
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.relax_temperature
    - sensor.vardagsrum_temperature
    - sensor.sovrum_temperature
    - sensor.malte_temperature
    - sensor.lina_temperature
#    - sensor.garage_temperature # Gives bad mean value

# Effekt och energi
- platform: template
  sensors:
    power:
      friendly_name: Effekt
      value_template: '{{ ((float(states("sensor.current_1")) + float(states("sensor.current_2")) + float(states("sensor.current_3")))*220) | int }}' # Should've been 236V but this seems more calibrated...
      unit_of_measurement: W
      icon_template: mdi:power-plug
- platform: integration
  name: Energy
  source: sensor.power
  unit_prefix: k
  round: 2

# Trafikverkets väderstationer
- platform: trafikverket_weatherstation
  name: Trafikverket Jörlanda
  api_key: !secret trafikverket_api_key
  station: Jörlanda
  monitored_conditions:
      - air_temp
      - road_temp
      - humidity
      - precipitation
      - wind_direction
      - wind_direction_text
      - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Kungälv
  # api_key: !secret trafikverket_api_key
  # station: Kungälv
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Tjörnbron
  # api_key: !secret trafikverket_api_key
  # station: Tjörnbron
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Ödsmål
  # api_key: !secret trafikverket_api_key
  # station: Ödsmål
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Fiskhamnsmotet
  # api_key: !secret trafikverket_api_key
  # station: Fiskhamnsmotet
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Delsjön
  # api_key: !secret trafikverket_api_key
  # station: Delsjön
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed

# Glue lock rest sensor, secrets:
# glue_resource: "https://user-api.gluehome.com/v1/locks/<lock-id>"
# glue_auth: "Api-Key <api-key>"
- platform: rest
  resource: !secret glue_resource
  name: friggebod_lock
  method: GET
  headers:
    Authorization: !secret glue_auth
  json_attributes:
    - description
    - batteryStatus
    - lastLockEvent
    - connectionStatus
  value_template: "OK"
- platform: template
  sensors:
    friggebod_lock_last_event:
      friendly_name: Last friggebod lock event
      value_template: "{{ state_attr('sensor.friggebod_lock', 'lastLockEvent')['eventType'] }}"
    friggebod_lock_battery:
      friendly_name: Friggebod lock battery
      value_template: "{{ state_attr('sensor.friggebod_lock', 'batteryStatus') }}"
    friggebod_lock_status:
      friendly_name: Friggebod lock connection status
      value_template: "{{ state_attr('sensor.friggebod_lock', 'connectionStatus') }}"
