# Weather and calculated/template sensors

# Calculated sensors
- platform: min_max
  name: Ute Temperature
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.sovrum_ute_temperature
    - sensor.malte_ute_temperature
    - sensor.lina_ute_temperature
    - sensor.entre_ute_temperature
#    - sensor.altan_ute_temperature # Gives bad mean value
- platform: min_max
  name: Inne Temperature
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.relax_temperature
    - sensor.vardagsrum_temperature
    - sensor.sovrum_temperature
    - sensor.malte_temperature
    - sensor.lina_temperature
#    - sensor.garage_temperature # Gives bad mean value

# Effekt och energi
- platform: template
  sensors:
    power:
      friendly_name: Effekt
      value_template: '{{ ((float(states("sensor.current_1")) + float(states("sensor.current_2")) + float(states("sensor.current_3")))*220) | int }}' # Should've been 236V but this seems more calibrated...
      unit_of_measurement: W
      icon_template: mdi:power-plug
- platform: integration
  name: Energy
  source: sensor.power
  unit_prefix: k
  round: 2

# Trafikverkets väderstationer
- platform: trafikverket_weatherstation
  name: Trafikverket Jörlanda
  api_key: !secret trafikverket_api_key
  station: Jörlanda
  monitored_conditions:
      - air_temp
      - road_temp
      - humidity
      - precipitation
      - wind_direction
      - wind_direction_text
      - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Kungälv
  # api_key: !secret trafikverket_api_key
  # station: Kungälv
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Tjörnbron
  # api_key: !secret trafikverket_api_key
  # station: Tjörnbron
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Ödsmål
  # api_key: !secret trafikverket_api_key
  # station: Ödsmål
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Fiskhamnsmotet
  # api_key: !secret trafikverket_api_key
  # station: Fiskhamnsmotet
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed
# - platform: trafikverket_weatherstation
  # name: Trafikverket Delsjön
  # api_key: !secret trafikverket_api_key
  # station: Delsjön
  # monitored_conditions:
      # - air_temp
      # - road_temp
      # - humidity
      # - precipitation
      # - wind_direction
      # - wind_direction_text
      # - wind_speed

# Glue Lock from https://github.com/uki-hassio/Glue-Lock¨
# Todo use user-api from  https://github.com/GlueHome/homebridge-plugin/blob/master/src/api/client.ts with api-key generated as described.
# - platform: rest
#   resource: !secret glue_resource
#   name: friggebod_sensor
#   method: GET
#   authentication: basic
#   username: !secret glue_user
#   password: !secret glue_pass
#   json_attributes:
#     - Status
#     - BatteryStatusAfter
#   value_template: 'OK'
# - platform: template
#   sensors:
#       friggebod_status:
#           value_template: '{{ states.sensor.friggebod_sensor.attributes["Status"] }}'
#       friggebod_battery:
#           value_template: '{{ (states.sensor.friggebod_sensor.attributes["BatteryStatusAfter"] | int /255 * 100) | int }}'
    