# Switch support

# RFXtrx433XL switches, needs host restart for automatic_add change
- platform: rfxtrx
  automatic_add: false
  signal_repetitions: 1
  devices:

    # Ljus
#    "0b11002d0000029a0d000060":
#      name: Sovrum
#      fire_event: true
#    "0b1100040000029a0b000050":
#      name: Linas fönster
#      fire_event: true
#    "0b1100480000029a0c000050":
#      name: Maltes fönster
#      fire_event: true
#    "0b1100d90000029a01000050":
#      name: Köksfönster
#      fire_event: true
#    "0b1100880000029a02000050":
#      name: Fönster
#      fire_event: true
    "0b1100110000029a0e010f50":
      name: TvLjus
      fire_event: true
#    "0b1100780000029a03000060":
#      name: Vitrinskåp
#      fire_event: true
#    "0b1100490000029a06000050":
#      name: Altanfönster
#      fire_event: true
#    "0b1100cf0000029a04000050":
#      name: Plantljus
#      fire_event: true
#    "0b1100520000029a05000060":
#      name: Plantfönster
#      fire_event: true
    "0b11002400055efa01020d60":
      name: Dator
      fire_event: true
    "0b1100940000029a07010f50":
      name: Altanjul
      fire_event: true
    "0b11000500bc0cfe01010f70": 
      name: Juleljus
      fire_event: true
#    "0b1100b70000029902010f50": # Brytare i switch
#    "0b1100780000029903010f50": # Brytare i switch
#    "0b1100ae0000029904010f50": # Brytare i switch
#    "0b1100df0000029901000050": # Old relaxgång switch
#    "0b11000600bc0cfe02010f70": # Up for grabs
#    "0b11000700bc0cfe03010f70": # Up for grabs

    # Laddare
    "0b1100770000029a09010f40":
      name: Laddare tvättrum
      fire_event: true
    "0b11008a0000029a0a000060":
      name: Laddare vardagsrum
      fire_event: true

    # Fjärrisar
#    "0b1100fa0005987a01000050": # Old huvudbrytare
    "0b11009d00ddbae201040f50":
      name: Dörrknapp
      fire_event: true
    "0b11003401b54ffa10010f60":
      name: Fjärr 1-1 dag
      fire_event: true
    "0b11008401b54ffa0f010f50":
      name: Fjärr 1-2 sovrum
      fire_event: true
    "0b11008c01b54ffa0e010f50":
      name: Fjärr 1-3 ute
      fire_event: true
    "0b1100a0011a67f610010f60":
      name: Fjärr 2-1 dag
      fire_event: true
    "0b1100a6011a67f60f010f50":
      name: Fjärr 2-2 sovrum
      fire_event: true
    "0b1100b1011a67f60e010f50":
      name: Fjärr 2-3 ute
      fire_event: true
    "0b1100dc03e567f610000050":
      name: Fjärr 3-1 dag
      fire_event: true
    "0b1100ea03e567f60f010f50":
      name: Fjärr 3-2 sovrum
      fire_event: true
    "0b1100f003e567f60e000050":
      name: Fjärr 3-3 ute
      fire_event: true
#    "0b11003b0005f86201020f60":
#      name: Gamla Sovrumsgångbrytaren
#    "0b11002400055efa01020d60":
#      name: Gamla Matbordsbrytaren
#    "0b11008e01a2024601010f50": S2
#      name: Matbord S2

    # Rörelsedetektorer
#    "0b11001300d65b160a010f50": # Nexa
#      name: IR Altan
#      fire_event: true

    # Klocka
    "0b11000b0000029b02010f60":
      name: Klocka Dörr
      fire_event: true
    "0b11003c0000029b04010f50":
      name: Klocka Fågel
      fire_event: true
    "0b1100490000029b03010f40":
      name: Klocka Musik
      fire_event: true
    "0b1100580000029b01010f60":
      name: Klocka Ring
      fire_event: true

    # Vattensensorer
    "0b11003701a2024602010f60":
      name: Vatten toa 1
      fire_event: true
    "0b1100de01a2024601010f60":
      name: Vatten toa 2
      fire_event: true
    "0b11008f01a2096a02010f50":
      name: Vatten badkar 1
      fire_event: true
    "0b1100ab01a2096a01010f50":
      name: Vatten badkar 2
      fire_event: true
    "0b11000001bfeb6601010f60":
      name: Vatten tvätt 1
      fire_event: true
    "0b11006d01bfeb6602010f60":
      name: Vatten tvätt 2
      fire_event: true
    "0b11003f01bfeada01010f50":
      name: Vatten disk 1
      fire_event: true
    "0b11003301bfeada02010f50":
      name: Vatten disk 2
      fire_event: true
    "0b11001e01bfe7e601010f50":
      name: Vatten dusch 1
      fire_event: true
    "0b11000001bfe7e602010f50":
      name: Vatten dusch 2
      fire_event: true


# Template switches
- platform: template
  switches:
    ac:
      friendly_name: Luftkonditionering
      value_template: "{{ is_state('input_boolean.ac', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.ac
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.ac

# Flux switches should contain at most 3-4 hue groups to perform reliable.
# I offset the interval to make them issue commands at different times.
# Use hue groups for warm/cold white lights instead of the bulbs for these to work properly.
# Note that all lights in a hue group will be turned on whenever one is on. Cannot use a single large group.
- platform: flux
  name: Dagsflux
  interval: 53
  start_colortemp: 3000
  sunset_colortemp: 2000
  stop_colortemp: 1600
  lights:
    - light.relax
    - light.vardagsrum
    - light.koksfonster
    - light.huego
    - light.matbord_upp
- platform: flux
  name: Sovflux
  interval: 67
  lights:
    - light.sovrumsgang
    - light.sanggavel
    - light.linas_vagg
    - light.maltes_vagg
- platform: flux
  name: Uteflux
  interval: 177
  start_time: '7:00'
  stop_time: '23:45'
  lights:
    - light.halltak
    - light.altanvagg
    - light.altanslinga
    - light.altanstolpe_1
    - light.altanstolpe_2
    - light.altanstolpe_3
    - light.altanbonsai
    - light.altanfontan
    - light.garageport
    - light.entrevagg
    - light.sexan
    - light.entrestolpe_v
    - light.entrestolpe_h
    - light.entrebuske

- platform: command_line
  switches:
    twinkly:
      command_on: "python3 /config/python_scripts/twinkly.py 192.168.0.28 on"
      command_off: "python3 /config/python_scripts/twinkly.py 192.168.0.28 off" 
#      command_state: "python3 /config/python_scripts/twinkly.py 192.168.0.28 state" # Will interfere with app; only one login token can be active at once...
      value_template: "{{ value == \"1\" }}"
      friendly_name: Twinkly
