# Switch support

# Template switches
- platform: template
  switches:
    ac:
      friendly_name: Luftkonditionering
      value_template: "{{ is_state('input_boolean.ac', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.ac
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.ac

# Flux switches should contain at most 3-4 hue groups to perform reliable.
# I offset the interval to make them issue commands at different times.
# Use hue groups for warm/cold white lights instead of the bulbs for these to work properly.
# Note that all lights in a hue group will be turned on whenever one is on. Cannot use a single large group.
- platform: flux
  name: Flygelflux
  interval: 52
  start_colortemp: 3600
  sunset_colortemp: 3000
  stop_colortemp: 1900
  lights:
    - light.flygelfonster
    - light.flygeltak_1
    - light.flygeltak_2
    - light.flygeltak_3
    - light.flygelgolv
#    - light.bordgo
    - light.signe
- platform: flux
  name: Relaxflux
  interval: 53
  start_colortemp: 3000
  sunset_colortemp: 2000
  stop_colortemp: 1600
  lights:
    - light.skarm
    - light.datatak
    - light.relaxtak
    - light.relaxgang
    - light.relaxannex
- platform: flux
  name: Vardagsflux
  interval: 54
  start_colortemp: 3600
  sunset_colortemp: 3000
  stop_colortemp: 1900
  lights:
    - light.tv
    - light.tak_v
    - light.tak_h
    - light.golvlampa
    - light.altanfonster
- platform: flux
  name: Köksflux
  interval: 55
  start_colortemp: 3000
  sunset_colortemp: 2000
  stop_colortemp: 1600
  lights:
    - light.koksfonster
    - light.matbord_upp
- platform: flux
  name: Sovflux
  interval: 67
  lights:
    - light.sovrumsgang
    - light.sanggavel
    - light.linas_vagg
    - light.maltes_vagg
- platform: flux
  name: Uteflux
  interval: 177
  start_colortemp: 3600
  sunset_colortemp: 3000
  stop_colortemp: 1900
  start_time: '7:00'
  stop_time: '23:45'
  lights:
    - light.halltak
    - light.flygelvagg
    - light.flygelsims_s1
    - light.flygelsims_s2
    - light.flygelsims_s3
    - light.flygelsims_n1
    - light.flygelsims_n2
    - light.flygelsims_n3
    - light.flygelsims_n4
    - light.altanvagg
    - light.altanslinga
    - light.extraslinga
    - light.altanstolpe_1
    - light.altanstolpe_2
    - light.altanstolpe_3
    - light.altanfontan
    - light.grilly
    - light.garageport
    - light.entrevagg
    - light.sexan
    - light.entrestolpe_1
    - light.entrestolpe_2
    - light.entrestolpe_3
    - light.entrestolpe_4
    - light.entrebuske

# Wake on LAN for SpelTV
- platform: wake_on_lan
  name: SpelTV
  mac: '04:7C:16:5B:81:54'
  host: '192.168.0.7'